"""Persistent state: records, the storage protocol and its implementations."""

from __future__ import annotations

from .base import Store
from .records import (
    APPROVED,
    AVAILABLE,
    BOOKED,
    BOOKING,
    CHECK_FAILED,
    EXPIRED,
    FAILED,
    HOLD_EXPIRED,
    JOB_DEAD,
    JOB_DONE,
    JOB_FAILED,
    JOB_FINISHED_STATES,
    JOB_QUEUED,
    JOB_RETRYING,
    JOB_RUNNING,
    OPEN_BOOKING_STATES,
    PENDING_APPROVAL,
    PREPARING,
    REJECTED,
    RUN_ERROR,
    RUN_INCOMPLETE,
    RUN_OK,
    RUN_RUNNING,
    SOLD_OUT,
    UNKNOWN,
    WATCHING,
    Booking,
    Candidate,
    Job,
    SearchRun,
    Want,
)
from .sqlite import SqliteStore

__all__ = [
    "APPROVED",
    "AVAILABLE",
    "BOOKED",
    "BOOKING",
    "CHECK_FAILED",
    "EXPIRED",
    "FAILED",
    "HOLD_EXPIRED",
    "JOB_DEAD",
    "JOB_DONE",
    "JOB_FAILED",
    "JOB_FINISHED_STATES",
    "JOB_QUEUED",
    "JOB_RETRYING",
    "JOB_RUNNING",
    "OPEN_BOOKING_STATES",
    "PENDING_APPROVAL",
    "PREPARING",
    "REJECTED",
    "RUN_ERROR",
    "RUN_INCOMPLETE",
    "RUN_OK",
    "RUN_RUNNING",
    "SOLD_OUT",
    "UNKNOWN",
    "WATCHING",
    "Booking",
    "Candidate",
    "Job",
    "SearchRun",
    "SqliteStore",
    "Store",
    "Want",
]
