"""The storage contract every backend implements.

The watcher, workers, web UI and Discord bot only ever talk to this protocol,
so the same code runs against SQLite on a laptop and DynamoDB on AWS. The
contract tests in ``tests/contract`` hold both implementations to it.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable, Protocol, Sequence, runtime_checkable

from .records import Booking, Candidate, Job, SearchRun, Want


@runtime_checkable
class Store(Protocol):
    def close(self) -> None: ...

    # --- wants --------------------------------------------------------------
    def add_want(self, **fields: Any) -> int: ...
    def update_want(self, want_id: int, **fields: Any) -> None: ...
    def delete_want(self, want_id: int) -> None: ...
    def get_want(self, want_id: int) -> Want | None: ...
    def list_wants(self, active_only: bool = False) -> list[Want]: ...
    def mark_want_searched(self, want_id: int) -> None: ...

    # --- candidates ---------------------------------------------------------
    def upsert_candidate(
        self,
        want_id: int,
        signature: str,
        path: list[str],
        legs: list[dict[str, Any]],
        stops: int,
        total_minutes: int,
        ground_transfer: bool,
        staggered_hours: float,
        departs_utc: datetime,
        window_opens_utc: datetime,
        window_closes_utc: datetime,
    ) -> tuple[int, bool]: ...
    def get_candidate(self, candidate_id: int) -> Candidate | None: ...
    def list_candidates(
        self, want_id: int | None = None, status: str | None = None, limit: int = 200
    ) -> list[Candidate]: ...
    def candidates_due_for_check(self, now: datetime, limit: int = 10) -> list[Candidate]: ...
    def record_check(
        self,
        candidate_id: int,
        result: str,
        detail: dict[str, Any],
        next_check_at: datetime | None,
    ) -> None: ...
    def mark_alerted(self, candidate_id: int) -> None: ...
    def expire_stale_candidates(self, now: datetime) -> int: ...

    # --- bookings -----------------------------------------------------------
    def create_booking(self, candidate_id: int, summary: str, detail: dict[str, Any]) -> int: ...
    def update_booking(self, booking_id: int, **fields: Any) -> None: ...
    def get_booking(self, booking_id: int) -> Booking | None: ...
    def list_bookings(
        self, statuses: Iterable[str] | None = None, limit: int = 100
    ) -> list[Booking]: ...
    def has_open_booking(self, candidate_id: int) -> bool: ...
    def count_open_bookings(self) -> int: ...
    def count_bookings_since(self, since: datetime) -> int: ...
    def expire_held_bookings(self, now: datetime) -> list[Booking]: ...

    # --- events -------------------------------------------------------------
    def log(self, kind: str, message: str, level: str = "info", **data: Any) -> None: ...
    def list_events(self, limit: int = 100, since_id: int = 0) -> list[dict[str, Any]]: ...
    def prune_events(self, keep_days: int = 30) -> int: ...

    # --- jobs ---------------------------------------------------------------
    def create_job(self, key: str, kind: str, want_id: int) -> bool: ...
    def get_job(self, key: str) -> Job | None: ...
    def claim_job(
        self, key: str, worker: str, lease_s: float, now: datetime | None = None
    ) -> Job | None: ...
    def finish_job(
        self,
        key: str,
        status: str,
        result: dict[str, Any] | None = None,
        error: str | None = None,
    ) -> None: ...
    def release_job(self, key: str, error: str) -> None: ...
    def list_jobs(self, status: str | None = None, limit: int = 100) -> list[Job]: ...
    def stale_jobs(
        self, older_than: datetime, statuses: Sequence[str] = ..., limit: int = 100
    ) -> list[Job]: ...
    def job_outcomes_since(self, since: datetime) -> dict[str, int]: ...

    # --- search runs --------------------------------------------------------
    def start_search_run(self, want_id: int, job_key: str | None) -> str: ...
    def finish_search_run(self, run_id: str, want_id: int, status: str, **metrics: Any) -> None: ...
    def list_search_runs(self, want_id: int | None = None, limit: int = 50) -> list[SearchRun]: ...

    # --- heartbeats ---------------------------------------------------------
    def beat(self, component: str, now: datetime | None = None) -> None: ...
    def heartbeats(self) -> dict[str, datetime]: ...
